<?php

namespace Plugin\HuaPayPlugin\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentMethodConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentMethodConfigRepository extends EntityRepository
{
}
