<?php

namespace Plugin\HuapayPlugin\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentMethodRepository extends EntityRepository
{
}
