Plugin\HuaPayPlugin\Entity\PaymentMethodConfig:
    type: entity
    table: plg_huapayplugin_paymentmethodconfig
    repositoryClass: Plugin\HuaPayPlugin\Repository\PaymentMethodConfigRepository
    indexes:
        payment_config_id_index:
            columns: [ payment_config_id ]
        eccube_payment_id_index:
            columns: [ eccube_payment_id ]
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
    fields:
        payment_config_id:
            type: integer
            nullable: true
            unsigned: false
        eccube_payment_id:
            type: integer
            nullable: true
            unsigned: false
        name:
            type: text
            nullable: true
        is_enabled:
            type: smallint
            nullable: true
            default: '1'
    lifecycleCallbacks: {  }
