Plugin\HuaPayPlugin\Entity\PaymentConfig:
    type: entity
    table: plg_huapayplugin_paymentconfig
    repositoryClass: Plugin\HuaPayPlugin\Repository\PaymentConfigRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
    fields:
        api_token:
            type: text
            nullable: true
        is_testing:
            type: smallint
            nullable: true
            default: '1'
        reference_prefix:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
